name: project notebook

dependencies:
- numpy
- pandas
- jupyterlab
- matplotlib
- scipy
- statsmodels
- pip
- us
- conda-forge::cmdstanpy
- conda-forge::us
- basemap
- conda-forge::mpl_toolkits
- pip:


